import React from "react";

export const metadata = {
  title: "Page not found",
  description: "Generated by create next app",
};

const notfound = () => {
  return <div>not-found</div>;
};

export default notfound;
