import { Button } from "@/components";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import { notFound } from "../../../../public/assets";

export const metadata = {
  title: "Page not found",
  description: "Generated by create next app",
};

const notfound = () => {
  return (
    <main className=" mt-[100px]">
      <div className=" container flex flex-col md:flex-row items-center md:justify-between">
        <div className=" ">
          <h1 className=" font-bold text-[28px]">لم يتم العثور على الصفحة</h1>
          <p className=" max-w-[400px] my-3">
            عفواً! يبدو أن هناك خطأ ما يبدو أننا لا نستطيع العثور على الصفحة
            التي تبحث عنها، تأكد من كتابة عنوان URL الصحيح
          </p>
          <Button href={"/ar/home"}>انتقل إلى الصفحة الرئيسية</Button>
        </div>
        <div>
          <Image src={notFound} alt="notfound"></Image>
        </div>
      </div>
    </main>
  );
};

export default notfound;
